#!/bin/bash

DEFAULT_BROWSER_FILE="$HOME/.config/dotfiles/default_browser.txt"
browser_to_launch=""

if [ -f "$DEFAULT_BROWSER_FILE" ]; then
    browser_to_launch=$(cat "$DEFAULT_BROWSER_FILE")
else
    default_browser=$(xdg-settings get default-web-browser)
    browser_to_launch=$(sed -n 's/^Exec=\([^ ]*\).*/\1/p' {~/.local,~/.nix-profile,/usr}/share/applications/$default_browser 2>/dev/null | head -1)
fi

if [[ "$browser_to_launch" =~ (firefox|zen|librewolf) ]]; then
  private_flag="--private-window"
else
  private_flag="--incognito"
fi

exec setsid uwsm-app -- "$browser_to_launch" "${@/--private/$private_flag}"
