#!/bin/bash

set -e

trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\n\nIf you need assistance, please seek help.\033[0m"' ERR

gum style --border normal --border-foreground 6 --padding "1 2" --margin "1 0" \
  "Ready to update Dotfiles?" \
  "" \
  "• You cannot stop the update once you start!" \
  "• Make sure you're not on battery power or have sufficient charge"

if ! gum confirm --default=false "Continue with update?"; then
  echo "Update cancelled"
  exit 0
fi

create-snapshot create || [ $? -eq 127 ]
update-git-repo
perform-update
